// Generated by https://quicktype.io

export interface Users {
    email:     string;
    password:  string;
    id:        number;
    updatedAt: string;
    active:    boolean;
    role:      string;
    username:  string;
    number:    number;
    firstname: string;
    lastname:  string;
    createdAt: string;
}
